-- This File is made by Pratyush Puri

-- I made the database name as 'sales' in my environment
-- ########################################################
use sales;

-- #################################
-- BASIC PROBLEMS
-- #################################


-- 	List all unique cities where customers are located

select distinct customer_city 
from customers
order by customer_city;

-- Count the number of orders placed in 2017

select count(order_id) as total_orders
from orders;

-- Find the total sales per category

select distinct product_category
from products;

-- Calculate the number of orders that were paid in installments

select count(order_id)
from payments
where  payment_installments > 1;

-- Count the number of customers from each state

select customer_state,count(customer_id) as `Total Customers`
from customers
group by customer_state
order by `Total Customers` desc;


-- #################################
-- INTERMEDIATE PROBLEMS
-- #################################


-- Calculate the number of orders per month in 2018

select month(order_purchase_timestamp) as Month, count(order_id) as `Total Orders`
from order_items
where year(order_purchase_timestamp) = 2018
group by month(order_purchase_timestamp)
order by Month;

-- Find the average number of products per order, group by customer city

select c.customer_city, round((avg(product_count)),2)  as avg_products_per_order
from (
	select oi.order_id, oi.customer_id, count(o.product_id) as product_count
    from order_items oi
    inner join orders o on oi.order_id = o.order_id
    group by oi.order_id, oi.customer_id
) as order_product_counts
inner join customers c on order_product_counts.customer_id = c.customer_id
group by c.customer_city;

-- Calculate the percentage of total revenue contributed by each product category

select p.product_category, round(( sum(o.price)),2) as category_revenue,
    round(sum(o.price) * 100.0 / sum(sum(o.price)) over(), 2) as percentage_of_total
from orders o
inner join products p on o.product_id = p.product_id
group by p.product_category;

-- Identify the correlation between product price and the number of times a product has been purchased.

select o.product_id, avg(o.price) as avg_price, count(*) as purchase_count
from orders o
group by o.product_id
order by purchase_count desc;

-- Calculate the total revenue generated by each seller, and rank them by revenue.

select o.seller_id, round((sum(o.price)),2)  as total_revenue,
    rank() over (order by sum(o.price) desc) as revenue_rank
from orders o
group by o.seller_id
order by revenue_rank;

-- #################################
-- ADVANCED PROBLEMS
-- #################################

-- Calculate the moving average of order values for each customer over their order history.

select oi.customer_id, oi.order_id, oi.order_purchase_timestamp, sum(o.price) as order_value,
    avg(sum(o.price)) over (
        partition by oi.customer_id 
        order by oi.order_purchase_timestamp 
        rows between unbounded preceding and current row
    ) as moving_avg_order_value
from order_items oi
inner join orders o on oi.order_id = o.order_id
group by oi.customer_id, oi.order_id, oi.order_purchase_timestamp
order by oi.customer_id, oi.order_purchase_timestamp;

-- Calculate the cumulative sales per month for each year.

select year(oi.order_purchase_timestamp) as year, month(oi.order_purchase_timestamp) as month,
    sum(o.price) as monthly_sales,
    sum(sum(o.price)) over (
        partition by year(oi.order_purchase_timestamp) 
        order by month(oi.order_purchase_timestamp)
    ) as cumulative_sales
from order_items oi
inner join orders o on oi.order_id = o.order_id
group by year(oi.order_purchase_timestamp), month(oi.order_purchase_timestamp)
order by year, month;

-- Calculate the year-over-year growth rate of total sales.

with yearly_sales as (
    select  year(oi.order_purchase_timestamp) as year, sum(o.price) as total_sales
    from order_items oi
    inner join orders o on oi.order_id = o.order_id
    group by year(oi.order_purchase_timestamp)
)
select current_year.year, current_year.total_sales, previous_year.total_sales as previous_year_sales,
    round(((current_year.total_sales - previous_year.total_sales) / previous_year.total_sales) * 100, 2) as yoy_growth_rate
from yearly_sales current_year
left join yearly_sales previous_year on current_year.year = previous_year.year + 1
order by current_year.year;

-- Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase.

with first_purchase as (
    select customer_id, min(order_purchase_timestamp) as first_order_date
    from order_items
    group by customer_id
),
repeat_purchase as (
    select distinct fp.customer_id
    from first_purchase fp
    inner join order_items oi on fp.customer_id = oi.customer_id
    where oi.order_purchase_timestamp > fp.first_order_date
    and oi.order_purchase_timestamp <= date_add(fp.first_order_date, interval 6 month)
)
select count(distinct fp.customer_id) as total_customers,
    count(distinct rp.customer_id) as retained_customers,
    round((count(distinct rp.customer_id) / count(distinct fp.customer_id)) * 100, 2) as retention_rate_percentage
from first_purchase fp
left join repeat_purchase rp on fp.customer_id = rp.customer_id;



-- Identify the top 3 customers who spent the most money in each year.

with customer_yearly_spending as (
    select oi.customer_id, year(oi.order_purchase_timestamp) as year,
        sum(o.price) as total_spent,
        row_number() over (
            partition by year(oi.order_purchase_timestamp) 
            order by sum(o.price) desc
        ) as rank_position
    from order_items oi
    inner join orders o on oi.order_id = o.order_id
    group by oi.customer_id, year(oi.order_purchase_timestamp)
)
select year, customer_id, total_spent, rank_position
from customer_yearly_spending
where rank_position <= 3
order by year, rank_position;










